name: 'Setup and Run Node.js App'
description: 'Setup Node.js and run a script'
inputs:
  node-version:
    description: 'Node.js version to set up'
    required: true
  max_entries:
    description: 'Maximum number of failed tests to output'
    required: false
    default: '20'
  xml_pattern:
    description: 'Glob pattern for finding XML files'
    required: true
    default: 'build/test-reports/test/**/*.xml'

outputs:
  failed_tests:
    description: 'JSON formatted summary of failed tests'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Install dependencies
      run: npm ci
      shell: bash
      working-directory: ./.github/actions/failed-tests-extractor
    - name: Set Environment Variables
      run: |
        echo "MAX_ENTRIES=${{ inputs.max_entries }}" >> $GITHUB_ENV
        echo "XML_PATTERN=${{ inputs.xml_pattern }}" >> $GITHUB_ENV
      shell: bash
    - name: Output results (debug)
      id: results-debug
      run: enode .github/actions/failed-tests-extractor/script.js
      shell: bash
      working-directory: ${{ github.workspace }} # スクリプト実行ディレクトリをプロジェクトのルートに設定
      env:
        NODE_PATH: ${{ github.workspace }}/.github/actions/failed-tests-extractor/node_modules

    - name: Output results
      id: results
      run: echo "failed_tests=$(node .github/actions/failed-tests-extractor/script.js)" >> $GITHUB_ENV
      shell: bash
      working-directory: ${{ github.workspace }} # スクリプト実行ディレクトリをプロジェクトのルートに設定
      env:
        NODE_PATH: ${{ github.workspace }}/.github/actions/failed-tests-extractor/node_modules
