name: Deploy to GitHub Pages (Only main page)

on:
  push:
    branches:
      - master
    paths:
      - 'pages/**'

jobs:
  deploy-pages:
    concurrency:
      group: push-to-gh-pages
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # NOTE: This won't change sub directories like /beta or /staging. See other workflows.
    - name: Build and deploy to gh-pages
      uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./pages
        keep_files: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
