name: Deploy to GitHub Pages (Only main page)

on:
  push:
    branches:
      - master
    paths:
      - 'pages/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build and deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3 # v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./pages
        keep_files: true
