name: Deploy to GitHub Pages (Only main page)

on:
  push:
    branches:
      - master
    paths:
      - 'pages/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and deploy to gh-pages
      uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
      with:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./pages
        publish_branch: gh-pages
        keep_files: true
