name: BETA Test

on:
  workflow_dispatch:
  push:

jobs:
  test:
    concurrency:
      group: beta-test
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: test
        run: ./gradlew clean test

      - name: check build directory
        if: success() || failure()
        run: ls -la build

      - name: check build directory
        if: success() || failure()
        run: ls -la build/test-results

      - name: check build directory
        if: success() || failure()
        run: ls -la build/test-results/test

      - name: Report failed tests
        if: success() || failure()
        id: failed-tests-extractor
        uses: ./.github/actions/failed-tests-extractor

      - name: check output
        if: success() || failure()
        run: echo "$result"
        env:
          result: ${{ steps.failed-tests-extractor.outputs.detailed_failures }}

      - name: Send custom JSON data to Slack workflow
        if: success() || failure()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'notify-test'
          payload: |
            {
              "attachments": [
                {
                  "color": "green",
                  "blocks": [
                    {
                      "type": "header",
                      "text": {
                        "type": "plain_text",
                        "text": "[${{ github.repository }}] ${{ env.STATUS }}",
                        "emoji": true
                      }
                    },
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*Job Url:*\n${{ env.RUN_URL }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Ref:*\n${{ github.ref_name }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Changes:*\n${{ env.CHANGES_LINK || 'N/A' }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Author:*\n<${{ github.server_url }}/${{ github.actor }}|${{ github.actor }}>"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          RUN_URL: ${{ github.server_url }}/${{github.repository}}/actions/runs/${{ github.run_id }}

      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: beta-test-results-${{ github.run_number }}
          path: build/allure-results
          retention-days: 1
          if-no-files-found: error

  deploy-test-result:
    needs: test
    if: success() || failure()
    uses: ./.github/workflows/deploy-test-result-to-pages.yml
    with:
      results-artifact-name: beta-test-results-${{ github.run_number }}
      env: beta
