name: STAGING Test

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
      - uses: Xotabu4/selenoid-github-action@v2
      - name: test
        run: ./gradlew clean tests_on_selenoid -Dbrowser_version="100.0" -Dbrowser_size="1920x1080" -Dbrowser_host="selenoid.autotests.cloud/wd/hub"
      - name: checkout gh-pages to get history
        uses: actions/checkout@v3
        if: success() || failure()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - uses: simple-elf/allure-report-action@58e6590adf6d8f196a0d771bf8a00e6921086a62 # v1.9
        if: success() || failure()
        with:
          gh_pages: gh-pages
          subfolder: staging
          allure_results: build/allure-results
          allure_report: allure-report
          allure_history: allure-history
          # TODO: Set report_url: domain/path/<env>. finally url is {{ report_url }}/4/index.html
      - name: Build and deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v2 # v4.0.0
        if: success() || failure()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          destination_dir: staging
