name: STAGING Test

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
      - uses: Xotabu4/selenoid-github-action@v2
      - name: test
        run: ./gradlew clean tests_on_selenoid -Dbrowser_version="100.0" -Dbrowser_size="1920x1080" -Dbrowser_host="selenoid.autotests.cloud/wd/hub"
      - name: checkout gh-pages to get history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          subfolder: staging
          allure_results: build/allure-results
          allure_report: allure-report
          allure_history: allure-history
          # TODO: Set report_url: domain/path/<env>. finally url is {{ report_url }}/4/index.html
      - name: Build and deploy to gh-pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        if: always()
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
          destination_dir: staging
