name: STAGING Test

on:
  workflow_dispatch:
  push:

jobs:
  test:
    concurrency:
      group: staging-test
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
      - uses: Xotabu4/selenoid-github-action@v2
      - name: test
        run: ./gradlew clean tests_on_selenoid -Dbrowser_version="100.0" -Dbrowser_size="1920x1080" -Dbrowser_host="selenoid.autotests.cloud/wd/hub"

      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: staging-test-results-${{ github.run_id }}
          path: build/allure-results
          retention-days: 1
          if-no-files-found: error

  deploy:
    concurrency:
      group: push-to-gh-pages
      cancel-in-progress: false
    runs-on: ubuntu-latest
    if: success() || failure()
    needs: test
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: staging-test-results-${{ github.run_id }}
          path: build/allure-results

      - name: checkout gh-pages to get history
        uses: actions/checkout@v3
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Extract repository name
        run: echo "REPOSITORY_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)" >> $GITHUB_ENV
      - uses: simple-elf/allure-report-action@58e6590adf6d8f196a0d771bf8a00e6921086a62 # v1.9
        with:
          gh_pages: gh-pages
          subfolder: staging # final result is in allure-history/staging
          allure_results: build/allure-results
          allure_report: allure-report
          allure_history: allure-history
          report_url: https://${{ github.repository_owner }}.github.io/${{ env.REPOSITORY_NAME }}/staging
          github_server_url: ${{ github.server_url }}
          keep_reports: 20
      - name: Build and deploy to gh-pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./allure-history/staging
          destination_dir: ./staging
          keep_files: false
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
