name: STAGING Test

on:
  workflow_dispatch:
  push:

jobs:
  test:
    concurrency:
      group: staging-test
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: test
        id: test
        run: ./gradlew clean test

      - name: Notify test results with urls to Slack
        if: success() || failure()
        uses: ./.github/actions/slack
        with:
          channel-id: 'notify-test'
          status: ${{ steps.test.outcome }}
          title: 'Test results STAGING'
          slack-token: ${{ secrets.SLACK_BOT_TOKEN }}
          env: staging
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: staging-test-results-${{ github.run_number }}
          path: build/allure-results
          retention-days: 1
          if-no-files-found: error

  deploy-test-result:
    needs: test
    if: success() || failure()
    uses: ./.github/workflows/deploy-test-result-to-pages.yml
    with:
      results-artifact-name: staging-test-results-${{ github.run_number }}
      env: staging
